name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  repack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware/

      - name: Show files
        run: find firmware/ -type f -name "*.uf2"

      - name: Upload raw uf2
        uses: actions/upload-artifact@v4
        with:
          name: firmware-stored
          path: firmware/*.uf2
          compression-level: 0   # Store only — no Deflate compression
