name: Build ZMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  repack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware/

      - name: List files
        run: find firmware/ -type f

      - name: Repack artifact without compression
        run: |
          cd firmware
          zip -0 -r ../firmware-store.zip .

      - name: Upload uncompressed firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware-store.zip
          overwrite: true
